# -*- coding: utf-8 -*-
"""non_linear_corr_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hu2XW7JL05YzndSLzYGaiCBA7rcyzZo-
"""

import pandas as pd

# 데이터 불러오기
df = pd.read_csv('train.csv')

# 대표값 계산
median_avg_token_length = df.loc[
    (df['average_token_length'].notnull()) & (df['average_token_length'] != 0),
    'average_token_length'
].median()

mean_unique_tokens = df.loc[
    (df['n_non_stop_unique_tokens'].notnull()) & (df['n_non_stop_unique_tokens'] != 0),
    'n_non_stop_unique_tokens'
].mean()

### Step 1. 세 변수 중 하나라도 0이면 나머지도 0
zero_mask = (
    (df['n_non_stop_words'] == 0) |
    (df['n_non_stop_unique_tokens'] == 0) |
    (df['average_token_length'] == 0)
)
df.loc[zero_mask, ['n_non_stop_words', 'n_non_stop_unique_tokens', 'average_token_length']] = 0

### Step 2. n_non_stop_words 와 average_token_length 관계

# 2-1. average_token_length만 결측이고, n_non_stop_words가 0이 아닌 경우
mask_atl_null = df['average_token_length'].isnull() & (df['n_non_stop_words'] != 0)
df.loc[mask_atl_null, 'average_token_length'] = median_avg_token_length

# 2-2. n_non_stop_words만 결측이고, average_token_length가 0이 아닌 경우
mask_nsw_null = df['n_non_stop_words'].isnull() & (df['average_token_length'] != 0)
df.loc[mask_nsw_null, 'n_non_stop_words'] = 1

# 2-3. 둘 다 결측인 경우
both_null = df['n_non_stop_words'].isnull() & df['average_token_length'].isnull()
df.loc[both_null, 'n_non_stop_words'] = 1
df.loc[both_null, 'average_token_length'] = median_avg_token_length

### Step 3. n_non_stop_words 와 n_non_stop_unique_tokens 관계

# 3-1. n_non_stop_words == 0이면 나머지도 0
mask_nsw_zero = df['n_non_stop_words'] == 0
df.loc[mask_nsw_zero, ['n_non_stop_unique_tokens', 'average_token_length']] = 0

# 3-2. n_non_stop_unique_tokens만 결측이고, n_non_stop_words가 0이 아닌 경우
mask_unt_null = df['n_non_stop_unique_tokens'].isnull() & (df['n_non_stop_words'] != 0)
df.loc[mask_unt_null, 'n_non_stop_unique_tokens'] = mean_unique_tokens

### 결과 확인
print(df[['n_non_stop_words', 'n_non_stop_unique_tokens', 'average_token_length']].isnull().sum())

df.to_csv('train_filled_3_variables.csv', index=False)

print(df[['n_non_stop_words', 'n_non_stop_unique_tokens', 'average_token_length']].isnull().sum())

